name: peviitor.ro
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  main
      - name: Fast FTP
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWD}}
          method: ftp
          local_dir: .
          remote_dir: .
